### ISSUE TITLE
Pongo filters plugin system

### ISSUE THREAD

**Issue by BobVanB** [HeavyHorst/remco#13]
Its nice to have backends pluggable, but i wouldlike if the filters also where pluggable.
This is supported in django, and would also like it. This way i don't have to worry about creating a filter that is 10 rows long. but import my custom filter and than do the work in there.

If i look at https://github.com/flosch/pongo2-addons, this will install a package and then I have to manually add a line to import the package. I want the application to this autocratically.

This way I can group multiple filters by functions or use.

Here is an example through i came up with the idea.
Through the consul and env backend plugin i get the following keys:
```
/database/username
/database/port
```
What i want is to translate the keys to cfg file, with the followint format:
`DATABASE_USERNAME = '<value>'

I almost got it with the current filters in remco, but i can't find a way to remove the first '_'.
```
{% for kv in getallkvs() %}
{{ kv.Key|split:"/"|join:"_"|upper }} = '{{ kv.Value }}'{% endfor %}
```
And what i want is to do the transformation in the plugin, with my own filter.
Than it looks like this:
```
{% for kv in getallkvs() %}
{{ kv.Key|toEnvVar }} = '{{ kv.Value }}'{% endfor %}
```

**Comment by HeavyHorst** [comment]
I like the idea.
That would curb the growing number of built-in filters.

I can imagine the following:
   1) Use the go plugin system.
   2) An RPC-based plugin system like the backend plugin system.
   3) Filter in an embedded scripting language (javascript, lua, anko ...)

I believe 3. would be easiest for the user.
I will experiment a bit.

**Comment by HeavyHorst** [comment]
I've just pushed af9258369e3240f8b2c950116b3678d20ac8b0ea and added support for custom javascript filters. 

https://github.com/HeavyHorst/remco/blob/master/docs/content/template/template-filters.md#custom-filters

Feel free to give it a try:
   1) you need to configure the filter directory in your config file
       - filter_dir  = "/etc/remco/filter.d"
   2) add the filter to this directory (the filename is also the filters name)
     toEnvVar.js with 
```javascript
In.split("/").join("_").substr(1).toUpperCase();
```

**Comment by HeavyHorst** [comment]
@BobVanB what do you think?

**Comment by BobVanB** [comment]
@HeavyHorst Hi, back from vacation.
Its looks nice and easy. +1 from me :D

**Comment by HeavyHorst** [comment]
Great !
Let me know if you encounter any problems.
