### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by ProTip** [HeavyHorst/remco#19]
Hola! I saw you mentioned in #18 that you weren't sure if other people were currently using this project. It's very compelling to me as an alternative to confd and I'm considering trying this out for the official Rundeck image I'm working on. It's currently experimental and utilizing confd. However, I have run into some.. _friction_ even trying to get a discussion going about a small change to the env backend, and of course it doesn't support distributing the keyspace out across multiple backends; that feature looks clutch.

Hopefully later in the week or this weekend I can take it for a spin and see how it goes, but first I was curious what your take on the viability of the project is for external use? The potential benefits over confd seem somewhat obvious.. Is there a hot new kid on the block in this space on not seeing?

Thanks for your time in advance if you can reply.

**Comment by HeavyHorst** [comment]
Hi! Please give remco a try and let me know how it's going. 
It should be a viable alternative to confd at this point.

I also like your idea with the double underscores: https://github.com/kelseyhightower/confd/issues/737
Would you mind creating a pull request here?: https://github.com/HeavyHorst/easykv

The only alternative to confd i know of is: https://github.com/hashicorp/consul-template
But consul-template only works with consul and vault.

**Comment by ProTip** [comment]
Cheers! Sorry for the late response. Will do on both accounts.

One thing I'm interested in is compos-ability for downstream image builders(myself included for our Pro builds). Different builds may have different plugins bundled into the image, as well as new or replacement configurations. With `confd` I can have my template resource definitions split out across files in a directory, however it appears that remco loads the single config file. Does this sound about right?

Currently I have a many to one, templates to config file, problem as well. With confd I'm solving that by generating templates for the same config file into a tmp directory, then `cat`ing them together into the final location.. This also helps with compos-ability for downstream builds, and I may be able to work around the single config file in a similar fashion..

**Comment by HeavyHorst** [comment]
Moin!

You can split your templatre resources across files with remco as well.
See: https://heavyhorst.github.io/remco/config/configuration-options/  - include_dir

Hope that helps!

**Comment by CrystalMethod** [comment]
I just wanted to let you know that we're basing our entire internal docker container infrastructure on remco. Thx foe the work.

**Comment by HeavyHorst** [comment]
Great! Let me know how it's going.
And don't hesitate to file issues if you encounter any problems.

**Comment by HeavyHorst** [comment]
@ProTip It's good to hear that!
I'm glad it all worked out.

If you have any questions about the PR's, feel free to ask.
