### ISSUE TITLE
Release is old

### ISSUE THREAD

**Issue by ProTip** [HeavyHorst/remco#23]
Took me a bit to figure out why the backend defaults weren't in the docs 😄 Looks like the latest release is from October 7th 2017; before the backend defaults were added.

I can use go get to continue my testing.

**Comment by HeavyHorst** [comment]
You're right. I'm on vacation from 20-30 August, I plan to cut a new release afterwards.

Until then you can see the documentation of master here: https://github.com/HeavyHorst/remco/tree/master/docs/content

**Comment by HeavyHorst** [comment]
Thanks for your patience. New update is out!
