### ISSUE TITLE
Macro errors written to template

### ISSUE THREAD

**Issue by ProTip** [HeavyHorst/remco#24]
I'm seeing output like this:
```
rundeck {
            [Error (where: execution) in /home/greg/scratch/docker-remco/remco/templates/jaas-loginmodule.conf | Line 7 Col 21 near 'getv'] key does not exist: /rundeck/jaas/ldap/providerurl

};
```
Probably related to this long-standing issue:
https://github.com/flosch/pongo2/issues/54

**Comment by HeavyHorst** [comment]
Sorry for the late response. This is exactly the issue you mentioned.
I will try to fix this on my fork of pongo2: https://github.com/HeavyHorst/pongo2

**Comment by HeavyHorst** [comment]
I think i fixed this. You can test this with latest master if you like.
Thanks for reporting this !
