### ISSUE TITLE
Request: make stagefile configurable

### ISSUE THREAD

**Issue by dsielert** [HeavyHorst/remco#27]
remco doesn't seem to like my .env configuration files as the stagefilename is the dest prepended with a '.' 
Workaround for now I found that works is to use 
```
 reload_cmd  = "cp /var/www/env /var/www/.env 
```

**Comment by HeavyHorst** [comment]
The stageFileName is always `ioutil.TempFile(filepath.Dir(s.Dst), "."+filepath.Base(s.Dst))` at the moment.

So if your destination file ist /var/www/env then your stageFile would be /var/www/.env.7643745 (something random).

You can then use this stageFile in your check_cmd like this:
**check_cmd(string, optional):
The command to check config. Use {{.src}} to reference the rendered source template.**

{{.src}} is the stageFile.

You can't use it that way? Do you have an example where you need a different behavior?
