### ISSUE TITLE
[Feature request] Support kubernetes authentication in vault backend

### ISSUE THREAD

**Issue by kammala** [HeavyHorst/remco#32]
Hi,

Thanks for an awesome tool!

It looks exactly as a tool I need(after working with `confd`), but it lacks k8s support for vault:
`confd` [supports](https://github.com/kelseyhightower/confd/blob/c9535ae93ab36ffce3b4d70dac68869b4dea8053/backends/vault/client.go#L86-L94) kubernetes authentication for vault backend.

It would be nice to have it in remco as well.

**Comment by HeavyHorst** [comment]
Thx for the pull request. I will update the go.mod file later and create a new pre-release for you to test.

**Comment by HeavyHorst** [comment]
Please try: https://github.com/HeavyHorst/remco/releases/tag/v0.12.0-beta.1

**Comment by kammala** [comment]
Thanks for a quick reaction, this fix works fine in my setup!
