### ISSUE TITLE
key does not exists for file backend when value is int or boolean

### ISSUE THREAD

**Issue by sp185432** [HeavyHorst/remco#33]
key does not exists for file backend when value is int or boolean

[0000]  INFO remco[6]: set file path backend=file filepath=/opt/better_chef_rundeck/bcr.json
[0000] ERROR remco[6]: createStageFileAndSync failed: create stage file failed: template execution failed: [Error (where: execution) in /etc/remco/templates/run.sh | Line 5 Col 96 near 'getv'] key does not exist: /bcr/port resource=run.sh.toml
[0000] ERROR remco[6]: not all templates could be rendered, trying again after 18 seconds resource=run.sh.toml

Using {{getenv("/bcr/port")}} for value replacement.

My json file bcr.json:
{
    "bcr": {
      "port": 3000
      }
}

**Comment by sp185432** [comment]
Sorry, using {{getv("/bcr/port")}}, not {{getenv("/bcr/port")}}

**Comment by HeavyHorst** [comment]
Keys and values need to be strings in all backends.

**Comment by sp185432** [comment]
Is there anyway to pull boolean or integer values to config from backend?

**Comment by HeavyHorst** [comment]
Do you need them as ints and bools or would it be ok to transform the values to strings?

**Comment by sp185432** [comment]
Its ok to be transformed as strings in this requirement.

Also any suggestions if we need to use these as ints and bools?

**Comment by HeavyHorst** [comment]
I think i can try to adjust the file backend so that files like 
```
{
    "bcr": {
        "port": 3000
    }
}
```
are parseable. 
Each value would be transformed to its string representation.

We could then, if neccessary, tranform these values back with a filter function (toInt, toBool or something like that).

What do you tink?

**Comment by sp185432** [comment]
Yes, this will be perfectly fine :-)

**Comment by HeavyHorst** [comment]
I just pushed https://github.com/HeavyHorst/easykv/commit/4d4fac1cf46d099faca5eb5c7ea368830a58b4b0
to easyKV. I will update remco in the next few days.

**Comment by sp185432** [comment]
Thanks @HeavyHorst

**Comment by HeavyHorst** [comment]
Remco uses the newest easykv release now. Other types should work now (if you build from master).

**Comment by sp185432** [comment]
Its working thanks.

**Comment by HeavyHorst** [comment]
Great!

**Comment by hatifnatt** [comment]
Is it possible to add info about this fix to v0.12.0-beta.2 release notes? I started with 'stable' 0.11.1 version and spend about an hour investigating this issue. Already prepared test setup to create new issue but finally found this one.

**Comment by HeavyHorst** [comment]
I added infos to the release notes.
