### ISSUE TITLE
[backend/file] Ability to specify headers for remote files

### ISSUE THREAD

**Issue by andreykaipov** [HeavyHorst/remco#34]
The use case is the remote config I'd like to poll isn't publicly accessible and requires authentication.

I'd create this issue for easykv, but I imagine it'll require changes to remco too as we'd need to change the file backend to accept a new setting and pass it along to easykv.

Lemme know if you'd be interested!

**Comment by HeavyHorst** [comment]
Sure! Are you interested in sending a pull request to easykv?

**Comment by andreykaipov** [comment]
Sure let me poke around a bit and see if I can add it without making a mess 😛

**Comment by HeavyHorst** [comment]
I just pushed: 82eedfb65b1dcdd04fab97f65fc7f285fa470208
Could you test this please?

I'll create a new beta version after I get your okay.

**Comment by andreykaipov** [comment]
Yup this is what I had when I tested it. Works great. 😄 Can we call the setting `httpheaders` though?

**Comment by HeavyHorst** [comment]
Sure! Could you send a PR with the change?

**Comment by HeavyHorst** [comment]
new release is out: https://github.com/HeavyHorst/remco/releases/tag/v0.12.0-beta.2
