### ISSUE TITLE
Add a filter that returns an array element by index

### ISSUE THREAD

**Issue by hatifnatt** [HeavyHorst/remco#38]
In Django template It's tricky to access specific array element by index if array is obtained as the result of applying a filter, because it's impossible to directly use index after filter.
I.e. I want only `third` part of the path
```
data = /first/second/third/fourth
data|split:'/'|slice:'2:3'|join:''
```
not very clear and intuitive, `slice` with single element still returns an array.

Better with custom JS filter, but not very portable, you need to supply your custom filter with your template:
```js
In[Param];
```
```
data|split:'/'|index:'2'
```
In Jinja2 element can be easily accessed by index or slice can be taken without additional filters:
```
data|split('/')[2]
```
Go template has an [`index`](https://golang.org/pkg/text/template/#hdr-Functions) function.

**Comment by HeavyHorst** [comment]
I added an index filter.

```
{{ "/home/user/test" | split:"/" | index:"1" }}
```

You can also use negative indexes like in python for example.
