### ISSUE TITLE
Add oneshot option

### ISSUE THREAD

**Issue by freeseacher** [HeavyHorst/remco#41]
I want to run remco with oneshot option. 
The case is to build shard configuration for terraform on my ci and i only need it one time. 
Just build config and exit. 
As far as i can see we already have an that option for backend configuration but not for template resource.

**Comment by HeavyHorst** [comment]
The onetime backend config should work i think.
If you set this to true, remco will only receive the template data once from the backend, renders the template and quit (if there is no other backend configured).

**Comment by freeseacher** [comment]
oh. i see. i have all my templates in one file and that cause that remco did not exit. 
moving one template to another file did the job.

Tnx!
