### ISSUE TITLE
Add support for indent for toYaml

### ISSUE THREAD

**Issue by freeseacher** [HeavyHorst/remco#46]
hi!
Please add support to setting starting indent for toYaml. 
like this one https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#filters-for-formatting-data 

i have to add something like 
`{{ config | toYaml(indent=2) }}`

**Comment by HeavyHorst** [comment]
Our yaml library supports custom indentation (https://godoc.org/gopkg.in/yaml.v3#Encoder.SetIndent).
Should be easy.

**Comment by HeavyHorst** [comment]
This is now possible with the latest master branch.

The Syntax:
`{{ config | toYAML:"indent=2" }}`
