### ISSUE TITLE
remco on multiple servers?

### ISSUE THREAD

**Issue by misu200** [HeavyHorst/remco#48]
Hello,
 
I am trying to get a feeling of how a Remco setup could look in production and some help would be gratefully appreciated:

In a production setting would I need install Remco on all my servers where I have .env files?
....or there could be a way Remco can read&write dst config files on remote servers?

Thanks,
Valentin

**Comment by HeavyHorst** [comment]
Hi,

you would need to install remco on each server where you want to create .env files.
