### ISSUE TITLE
Vault templating

### ISSUE THREAD

**Issue by naguam** [HeavyHorst/remco#58]
Hello,
In vault (unsealed and accessible via HTTP API using curl).

In my vault in /secret/n2 is stored `key=value`.
Via the HTTP API I can access it (using the hashicorp doc) using http://127.0.0.1:8200/v1/secret/data/n2.

I saw on the readme array that vault don't support prefix so I did not set prefix.

I didn't success with my remco resource.
```
[[resource]]
  name = "Vault"
  [[resource.template]]
    src = "/etc/remco/templates/key"
    dst = "/<path>/key"
    make_directories = true
    mode = "0644"
  [resource.backend]
    [resource.backend.vault]
      node = "http://172.0.0.1:8200"
      auth_type = "token" 
      auth_token = "<my_token>"
      watch = true
      keys = ["/v1/secret/data/n2"]
      onetime = false
      interval = 1
```
Tried many keys (same key as in the code above without v1, or/and data or with just n2)
The key template is just `{{ getv("/v1/secret/data/n2") }}` (modified in concordance as above).

Thank You in advance.
Regards.

**Comment by HeavyHorst** [comment]
Here is an example from our integration tests:
https://github.com/HeavyHorst/remco/tree/master/integration/vault

does that help?

**Comment by naguam** [comment]
I have already seen this, but it did not really help me (because I can't compare with the organisation/tree of a corresponding vault kv example).
Also with vault there is a notion of secret engine with the first prefix defining different secret engines access (it is also possible to set custom secret engine prefix), and in this exemple, I don't think /database is an engine prefix (but I can be wrong).
If i'm right, is there a default prefix in the remco vault module ?

I don't know the sources but maybe there is a place where a request url is built with the infos provided ? (which can help me to know what to enter in my conf files)

**Comment by naguam** [comment]
I having done many tests, I found how to it, I'm going to close the issue.

For this issue to be useful for anyone who comes here, I'm posting here the structure of the fault and the key in the configuration.

In Vault (using the vault cli).
My secrets are stored at the secret path and here for the example at secret/n2, there is content=value. This is placed in vault using `vault kv put secret/n2 content = value`.

To access to the key using the remco vault engine.
In the ressource backend configuration, the corresponding key is `keys = ["secret/data/n2"]`
But in the template to get the value juste using getv, `{{ get(secret/data/n2/content) }}`
(Yes it's not the same as what is placed in the key place in the config).
It was not a big thing, but It's a detail that matters :+1: 

Thank you for your answers.

**Comment by HeavyHorst** [comment]
Thanks for figuring that out!
