### ISSUE TITLE
get keys from etcd and loop through

### ISSUE THREAD

**Issue by swood** [HeavyHorst/remco#67]
Hi.

I'm trying to migrate my configuration from Confd to Remco and I'm stuck on the simple operation which has been described in the documentation.
There is a function "toJson" and I wrote simple configuration:

> {% for i in gets("/registry/services/specs/development/*filter*") | toJson %}
        value: {{ i.Value }}
{% endfor %}

The Remco wrote into the log file:

>  time="2021-01-08T02:44:28+03:00" level=error msg="createStageFileAndSync failed: create stage file failed: set.FromFile(/etc/remco/resource.d/my.tmpl) failed: [Error (where: parser) in /etc/remco/resource.d/my.tmpl | Line 1 Col 67 near 'toJson'] Filter 'toJson' does not exist." prefix="./remco_linux[41390]" resource=nginx

What's wrong in my example and why the documentation so poor to describe the examples with different backends?!

**Comment by HeavyHorst** [comment]
Sorry for the lacking documentation.
Can you try toJSON instead of toJson?
