### ISSUE TITLE
Allow "onetime" to be forced from command line or allow only specific backends (or both)

### ISSUE THREAD

**Issue by andrewheberle** [HeavyHorst/remco#74]
The use case for this is having initial/early onetime configuration via environment vars when a container starts (potentially via a containers entrypoint script), with ongoing config updates via etcd/consul etc with remco running as a daemon.

This is currently possible to achieve but it requires having one config file and set of resources for the "oneshot" part and another config for the ongoing part.

It would be great if we could have something similar to the following:

```sh
remco -onetime -backends env
```

The idea being that `-backends` is a comma separated list of backends to run/allow, with others being ignored, while `-onetime` would force "onetime" as "true" regardless of the actual resource config.

To be honest the `-backends` option would fulfil my needs as I would be having my "env" resources with "onetime = true" anyway.

**Comment by sseide** [comment]
we have the same use case as @andrewheberle, but for us the `-onetime` command line param would help most...

**Comment by sseide** [comment]
@HeavyHorst i tried to implement the `-onetime` flag but have a question here. To loop over all resources and their backends to set `Onetime` before the configurations are used i have to extend the `BackendConnector` interface to either
```
type BackendConnector interface {
	Connect() (Backend, error)
	GetBackend() (*Backend)
}
```
or 
```
type BackendConnector interface {
	Connect() (Backend, error)
	SetBackendOnetime() ()
}
```
What do you prefer?

**Comment by HeavyHorst** [comment]
@sseide I think I would prefer the first option as it is more general.
